# Site settings 配置站点
title: Ray Eldath's Blog
description: '热爱知识的高中生。</br> 高二 / 爵士鼓 / 编程 / Java / Kotlin / 科幻'
keyword: 'ray eldath, eldath, kotlin, java, program, computer, tech, sci-fi'
url: 'http://ray-eldath.tech' # your host

# if you don't need baseurl, you should leave this value blank.
baseurl: ''

# Navigation links
nav:
  home: '/'
  tags: '/tags.html'

# Footer
footer:
  since: 2017

# Author 配置博主信息
author: 'Ray Eldath'
nickname: 'Eldath'
bio: '祈愿的碎片啊 请成为永恒的存在'
avatar: 'http://ray-eldath.image.alimmdn.com/basic/avatar.png'

# Search
search: true

# Night mode
nightMode: true

# Comments
disqus: false
disqus_url: 'https://liaokeyu.disqus.com/embed.js'

livere: true
livere_uid: MTAyMC8yODEwMC80Njcz

# Reward 赞赏功能 by Ray-Eldath
reward:
  enable: true
  reward_comment: '真诚赞赏 手有余香'
  wechatpay: 'http://ray-eldath.image.alimmdn.com/basic/wechatpay.jpg'
  alipay: 'http://ray-eldath.image.alimmdn.com/basic/alipay.jpg'

# b2t 回到顶部 by Ray-Eldath
b2t: true

# MathJax 公式支持
mathjax: true

# Share
social-share: true
social-share-items: ['wechat', 'weibo', 'douban', 'twitter']

# theme color 主题皮肤
theme-color: 'default'  # pink or default

# Post header background patterns (when the post no cover): circuitBoard, overlappingCircles, food, glamorous, ticTacToe, seaOfClouds
postPatterns: 'circuitBoard'

# SNS settings 配置社交网站url: email, weibo, zhihu, twitter, instagram, juejin, github, douban, facebook, dribble, uicn, jianshu, medium, linkedin
sns:
  email: 'mailto:ray.eldath@aol.com'
  zhihu: '//www.zhihu.com/people/eldath-ray/activities'
  github: '//github.com/Ray-Eldath'
  twitter: '//twitter.com/ray_eldath'

# Tags 设置标签
recommend-tags: true # whether or not display recommend-tags on the sidebar
recommend-condition-size: 12 # a tag will be recommended if the size of it is more than this value

# Build settings
paginate: 6
paginate_path: 'page:num'
exclude: ['node_modules', 'dev', 'package.json', 'gulpfile.js', '.gitignore', 'README.md']

# Markdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM

# RSS
RSS: true

# Permalink
# See: https://github.com/kaeyleo/jekyll-theme-H2O/issues/35
permalink: /:year/:month/:day/:title.html

# Plugins
plugins: [jekyll-paginate]
