blank_issues_enabled: false
contact_links:
  - name: Gitter
    url: https://gitter.im/hexo-theme-icarus/community
    about: Redirect your Icarus usage questions to Gitter.
  - name: Gitter
    url: https://gitter.im/hexo-theme-icarus/community
    about: 与Icarus使用相关的问题请转至这里。
  - name: Bug Report
    url: https://github.com/ppoffice/hexo-theme-icarus/issues/new?template=bug_report.md
    about: Please follow this template if you are reporting a bug, or your issue may be closed without further notice.
  - name: Bug反馈
    url: https://github.com/ppoffice/hexo-theme-icarus/issues/new?template=Bug反馈.md
    about: 请按照模板填写Bug反馈，否则你的Issue可能会被直接关闭。
  - name: Feature Request
    url: https://github.com/ppoffice/hexo-theme-icarus/issues/new?template=feature_request.md
    about: Please follow this template if you are requesting a new feature, or your issue may be closed without further notice.
  - name: 功能建议
    url: https://github.com/ppoffice/hexo-theme-icarus/issues/new?template=功能建议.md
    about: 请按照模板填写功能建议，否则你的Issue可能会被直接关闭。