# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        position: left
        type: profile
        author: Ray Eldath
        author_title: 迷茫max......
        location:
        avatar: /img/avatar.jpg
        follow_link: 'https://t.me/kaworunagisa17'
        social_links:
            GitHub:
                icon: fab fa-github
                url: 'https://github.com/Ray-Eldath'
            Telegram Channel:
                icon: fab fa-telegram
                url: 'https://t.me/kaworunagisa17'
            Email:
                icon: fas fa-inbox
                url: 'mailto://ray.eldath@outlook.com'
            RSS:
                icon: fas fa-rss
                url: atom.xml
    -
        position: left
        type: links
        links:
            我的朋友们: /friends
            知乎（已不活跃）: https://zhihu.com/people/eldath-ray
            B站（空）: https://space.bilibili.com/45485880
            推特（不告诉你）: https://twitter.com/404
            很帅的域名: https://han.ninha/