# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    -
        position: left
        type: profile
        author: Ray Eldath
        author_title: DB & Systems
        location: Guangzhou, China
        avatar: /img/avatar.jpg
        follow_link: 'https://t.me/kaworunagisa17'
        social_links:
            GitHub:
                icon: fab fa-github
                url: 'https://github.com/Ray-Eldath'
            Telegram Channel:
                icon: fab fa-telegram
                url: 'https://t.me/kaworunagisa17'
            Twitter:
                icon: fab fa-twitter
                url: 'https://twitter.com/nagisakaworu17'
            Email:
                icon: fas fa-envelope-square
                url: 'mailto://ray.eldath@outlook.com'
            RSS:
                icon: fas fa-rss
                url: atom.xml