# Version of the configuration file
version: 4.0.0
# Icarus theme variant, can be "default" or "cyberpunk"
variant: default
# Path or URL to the website's logo
logo: /img/logo.png
# Page metadata configurations
head:
    # URL or path to the website's icon
    favicon: /img/favicon.ico
    # Web application manifests configuration
    # https://developer.mozilla.org/en-US/docs/Web/Manifest
    manifest:
        # Name of the web application (default to the site title)
        name: 
        # The displayed name of the web application
        # when there is not enough space to display full name
        short_name: 
        # The start URL of the web application
        start_url: 
        # The default theme color for the application
        theme_color: 
        # A placeholder background color for the application page to display
        # before its stylesheet is loaded
        background_color: 
        # The preferred display mode for the website
        display: standalone
        # Image files that can serve as application icons for different contexts
        icons:
            -
                # The path to the image file
                src: ''
                # A string containing space-separated image dimensions
                sizes: ''
                # A hint as to the media type of the image
                type: 
    # Open Graph metadata
    # https://hexo.io/docs/helpers.html#open-graph
    open_graph:
        # Page title (og:title) (optional)
        # You should leave this blank for most of the time
        title: 
        # Page type (og:type) (optional)
        # You should leave this blank for most of the time
        type: blog
        # Page URL (og:url) (optional)
        # You should leave this blank for most of the time
        url: 
        # Page cover (og:image) (optional)
        # You should leave this blank for most of the time
        image: 
        # Site name (og:site_name) (optional)
        # You should leave this blank for most of the time
        site_name: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page description (og:description) (optional)
        # You should leave this blank for most of the time
        description: 
        # Twitter card type (twitter:card)
        twitter_card: summary_large_image
        # Twitter ID (twitter:creator)
        twitter_id: "@nagisakaworu17"
        # Twitter Site (twitter:site)
        twitter_site: "@nagisakaworu17"
        # Google+ profile link (deprecated)
        google_plus: 
        # Facebook admin ID
        fb_admins: 
        # Facebook App ID
        fb_app_id: 
    # Structured data of the page
    # https://developers.google.com/search/docs/guides/intro-structured-data
    structured_data:
        # Page title (optional)
        # You should leave this blank for most of the time
        title: 
        # Page description (optional)
        # You should leave this blank for most of the time
        description: 
        # Page URL (optional)
        # You should leave this blank for most of the time
        url: 
        # Page author (article:author) (optional)
        # You should leave this blank for most of the time
        author: 
        # Page images (optional)
        # You should leave this blank for most of the time
        image: 
    # Additional HTML meta tags in an array
    meta:
        # Meta tag specified in <attribute>=<value> style
        # E.g., name=theme-color;content=#123456 => <meta name="theme-color" content="#123456">
        - ''
    # URL or path to the website's RSS atom.xml
    rss: /atom.xml
# Page top navigation bar configurations
navbar:
    # Naviagtion menu items
    menu:
        主页: /
        归档: /archives
        分类: /categories
        标签: /tags
        留言板: /messages
        关于我👦: /about
        朋友们🎉: /friends
    # Links to be shown on the right of the navigation bar
    #links:
    #    Download on GitHub:
    #        icon: fab fa-github
    #        url: 'https://github.com/ppoffice/hexo-theme-icarus'
# Page footer configurations
footer:
    # Links to be shown on the right of the footer section
    links:
        本站所有文章基于 CC-BY-NC 4.0 协议授权:
            icon: fab fa-creative-commons
            url: 'https://creativecommons.org/licenses/by-nc/4.0/'
# Article related configurations
article:
    # Code highlight settings
    highlight:
        # Code highlight themes
        # https://github.com/highlightjs/highlight.js/tree/master/src/styles
        theme: atom-one-dark
        # Show copy code button
        clipboard: true
        # Default folding status of the code blocks. Can be "", "folded", "unfolded"
        fold: unfolded
    # Whether to show estimated article reading time
    readtime: true
    # Article licensing block
    licenses:
        'CC BY-NC 4.0':
            icon: fab fa-creative-commons-nc
            url: 'https://creativecommons.org/licenses/by-nc/4.0/'
# Search plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Search/
search:
    type: insight
# Comment plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Comment/
comment:
    type: valine
    app_id: mlvRhOYGPn7xXJKPMcz0ratS-gzGzoHsz
    app_key: DmO8z8RWunPvzkRmNEFOyn2c
    meta: ["nick", "mail", "link"]
    avatar: retro
    required_fields: ["nick", "mail"]
# Donate plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Donation/
donates:
    # "Afdian.net" donate button configurations
    #-
    #    type: afdian
    #    # URL to the "Afdian.net" personal page
    #    url: ''
    # Alipay donate button configurations
    #-
    #    type: alipay
    #    # Alipay qrcode image URL
    #    qrcode: ''
    ## Patreon donate button configurations
    #-
    #    type: patreon
    #    # URL to the Patreon page
    #    url: ''
    # Paypal donate button configurations
    #-
    #    type: paypal
    #    # Paypal business ID or email address
    #    business: ''
    #    # Currency code
    #    currency_code: USD
    # Wechat donate button configurations
    -
        type: wechat
        # Wechat qrcode image URL
        qrcode: /img/mm_reward_qrcode_1606242853784.png
    # "Buy me a coffee" donate button configurations
    -
        type: buymeacoffee
        # URL to the "Buy me a coffee" page
        url: 'https://www.buymeacoffee.com/RayEldath'
# Share plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/Share/
share:
    type: addtoany
# Sidebar configurations.
# Please be noted that a sidebar is only visible when it has at least one widget
sidebar:
    # Left sidebar configurations
    left:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: true
    # Right sidebar configurations
    right:
        # Whether the sidebar sticks to the top when page scrolls
        sticky: false
# Sidebar widget configurations
# http://ppoffice.github.io/hexo-theme-icarus/categories/Widgets/
widgets:
    # Profile widget configurations
    -
        # Where should the widget be placed, left sidebar or right sidebar
        position: left
        type: profile
        author: Ray Eldath
        author_title: 迷茫max......
        location:
        avatar: /img/avatar.jpg
        follow_link: 'https://t.me/kaworunagisa17'
        social_links:
            GitHub:
                icon: fab fa-github
                url: 'https://github.com/Ray-Eldath'
            Telegram Channel:
                icon: fab fa-telegram
                url: 'https://t.me/kaworunagisa17'
            Email:
                icon: fas fa-inbox
                url: 'mailto://ray.eldath@outlook.com'
            RSS:
                icon: fas fa-rss
                url: atom.xml
    -
        position: left
        type: links
        links:
            我的朋友们: /friends
            知乎（已不活跃）: https://zhihu.com/people/eldath-ray
            B站（空）: https://space.bilibili.com/45485880
            推特（不告诉你）: https://twitter.com/404
            很帅的域名: https://han.ninha/
         
    -
        position: right
        type: recent_posts
    -
        position: right
        type: categories
    -
        position: right
        type: tags
    #-
    #    position: left
    #    type: adsense
    #    # AdSense client ID
    #    client_id: ''
    #    # AdSense AD unit ID
    #    slot_id: ''
# Plugin configurations
# https://ppoffice.github.io/hexo-theme-icarus/categories/Plugins/
plugins:
    # Enable page startup animations
    animejs: true
    # Show the "back to top" button
    back_to_top: true
    # Baidu Analytics plugin settings
    # https://tongji.baidu.com
    baidu_analytics:
        # Baidu Analytics tracking ID
        tracking_id: 
    # Bing Webmaster Tools plugin settings
    # https://www.bing.com/toolbox/webmaster/
    bing_webmaster:
        # Bing Webmaster Tools tracking ID in the <meta> tag
        tracking_id: 
    # BuSuanZi site/page view counter
    # https://busuanzi.ibruce.info
    busuanzi: false
    # CNZZ statistics
    # https://www.umeng.com/web
    cnzz:
        # CNZZ tracker id
        id: 
        # CNZZ website id
        web_id: 
    # Alerting users about the use of cookies
    # https://www.osano.com/cookieconsent/
    #cookie_consent:
    #    # The compliance type. Can be "info", "opt-in", or "opt-out"
    #    type: info
    #    # Theme of the popup. Can be "block", "edgeless", or "classic"
    #    theme: edgeless
    #    # Whether the popup should stay static regardless of the page scrolls
    #    static: false
    #    # Where on the screen the consent popup should display
    #    position: bottom-left
    #    # URL to your site's cookie policy
    #    policyLink: 'https://www.cookiesandyou.com/'
    # Enable the lightGallery and Justified Gallery plugins
    gallery: true
    # Google Analytics plugin settings
    # https://analytics.google.com
    google_analytics:
        # Google Analytics tracking ID
        tracking_id: UA-97484560-2
    # Hotjar user feedback plugin
    # https://www.hotjar.com/
    hotjar:
        # Hotjar site id
        site_id: 
    # Enable the KaTeX math typesetting supprot
    # https://katex.org/
    katex: false
    # Enable the MathJax math typesetting support
    # https://www.mathjax.org/
    mathjax: true
    # Enable the Outdated Browser plugin
    # http://outdatedbrowser.com/
    outdated_browser: true
    # Show a progress bar at top of the page on page loading
    progressbar: true
    # Statcounter statistics
    # https://statcounter.com/
    statcounter:
        # Statcounter project id
        project: 
        # Statcounter project security code
        security: 
    # Twitter conversion tracking plugin settings
    # https://business.twitter.com/en/help/campaign-measurement-and-analytics/conversion-tracking-for-websites.html
    #twitter_conversion_tracking:
    #    # Twitter Pixel ID
    #    pixel_id: 
# CDN provider settings
# https://ppoffice.github.io/hexo-theme-icarus/Configuration/Theme/speed-up-your-site-with-custom-cdn/
providers:
    # Name or URL template of the JavaScript and/or stylesheet CDN provider
    cdn: cdnjs
    # Name or URL template of the webfont CDN provider
    fontcdn: google
    # Name or URL of the fontawesome icon font CDN provider
    iconcdn: "https://cdn.bootcdn.net/ajax/libs/font-awesome/5.15.1/css/all.min.css"
